import QtQuick 2.9

Item {
    readonly property string app_title: "Nearby"
    readonly property string nearByPlaces: qsTr("Nearby places")
    readonly property string nearByPlacesLowercase: qsTr("nearby places")
    readonly property string search: qsTr("search")
    readonly property string placesOfInterest: qsTr("places of interest in")
    readonly property string within: qsTr("within")
    readonly property string searchPlaceHolder: qsTr("Type to search nearby places")
    readonly property string noNetwork: qsTr("No internet connection detected.")
    readonly property string noLocationAccess: qsTr("Please enable location access.")
    readonly property string accessingLocation: qsTr("Accessing your location...")
    readonly property string searching: qsTr("Searching...")
    readonly property string allow: qsTr("Allow")
    readonly property string walk: qsTr("Walk")
    readonly property string drive: qsTr("Drive")
    readonly property string noPlacesFound: qsTr("No places found")
    readonly property string noPlacesFoundWithin: qsTr("No places found within")
    readonly property string noPhoneFound: qsTr("No phone found")
    readonly property string noWebsiteFound: qsTr("No website found")
    readonly property string noTypeFound: qsTr("No Type found")
    readonly property string close: qsTr("Close")
    readonly property string apply: qsTr("Apply")
    readonly property string distance: qsTr("Distance")
    readonly property string category: qsTr("Category")
    readonly property string title: qsTr("Title")
    readonly property string all: qsTr("All")
    readonly property string food: qsTr("Food")
    readonly property string hotel: qsTr("Hotels")
    readonly property string library: qsTr("Libraries")
    readonly property string cinema: qsTr("Cinema")
    readonly property string hospital: qsTr("Hospitals")
    readonly property string shops: qsTr("Shops")
    readonly property string shopsAndServices: qsTr("Shops and Services")
    readonly property string gas: qsTr("Gas")
    readonly property string bank: qsTr("Banks")
    readonly property string foodLowercase: qsTr("food places")
    readonly property string hotelLowercase: qsTr("hotels")
    readonly property string libraryLowercase: qsTr("libraries")
    readonly property string cinemaLowercase: qsTr("cinema")
    readonly property string hospitalLowercase: qsTr("hospitals")
    readonly property string shopsLowercase: qsTr("shops")
    readonly property string shopsAndServicesLowercase: qsTr("shops and services")
    readonly property string gasLowercase: qsTr("gas stations")
    readonly property string bankLowercase: qsTr("banks")
    readonly property string sortBy: qsTr("Sort by")
    readonly property string searchDistance: qsTr("Search distance")
    readonly property string settings: qsTr("Settings")
    readonly property string filters: qsTr("Filters")
    readonly property string gettingRoute: qsTr("Getting route")
    readonly property string directionsTo: qsTr("Directions to")
    readonly property string directions: "Directions"
    readonly property string nearMe: qsTr("near me")
    readonly property string no: qsTr("No")
    readonly property string found: qsTr("found")
    readonly property string inWord: qsTr("in")
    readonly property string tapOnCategory: qsTr("Tap on a category")
    readonly property string offline: qsTr("You are offline. Check your connection")
    readonly property string locationPermission: qsTr("Nearby needs to access your location")
    readonly property string call: qsTr("Call")
    readonly property string website: qsTr("Website")
    readonly property string missingCredentials: qsTr("Missing Route Service Credentials")
    readonly property string credits: qsTr("This app was built using AppStudio for ArcGIS. Mapping API provided by Esri.")
    readonly property string about: qsTr("About")
    readonly property string description: qsTr("Description")
    readonly property string accessConstraints: qsTr("Access and Use Constraints")
    readonly property string appVersion: qsTr("App Version")
    readonly property string aboutTheApp: qsTr("About the App")
    readonly property string ok: qsTr("Ok")
    readonly property string routeCredInstructions: qsTr("You need to add your routing services credentials in RouteView.qml")
}
