/*global define */
/*
 | Copyright 2014 Esri
 |
 | Licensed under the Apache License, Version 2.0 (the "License");
 | you may not use this file except in compliance with the License.
 | You may obtain a copy of the License at
 |
 |    http://www.apache.org/licenses/LICENSE-2.0
 |
 | Unless required by applicable law or agreed to in writing, software
 | distributed under the License is distributed on an "AS IS" BASIS,
 | WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 | See the License for the specific language governing permissions and
 | limitations under the License.
 */
define({
    root: ({
        tagHeaderText: "Tags",
        expandGroupDescText: "More",
        shrinkGroupDescText: "Less",
        layoutText: "Layout",
        signInText: "Sign In",
        signOutText: "Sign Out",
        showNullValue: "N/A",
        detailsDisplayText: "Details",
        sortByText: "Sort by",
        sortByViewText: "Views",
        sortByDateText: "Date",
        sortByNameText: "Name",
        gridViewTitle: "Grid view",
        listViewTitle: "List view",
        appHeaderTitle: "Home",
        allText: "ALL",
        orgText: "ORG",
        grpText: "GRP",
        groupLogoText: "Group Logo",
        appTypeText: "Type",
        appOwnerText: "Owner",
        tryItButtonText: "View",
        downloadButtonText: "Download",
        appDesText: "Description",
        reviewText: "Comments",
        itemDetailsLegendTab: "LEGEND",
        itemDetailsInfoTab: "INFO",
        tagsText: "Tags",
        sizeText: "Size",
        accessConstraintsText: "Access and Use Constraints",
        numberOfCommentsText: "Comments",
        numberOfRatingsText: "Ratings",
        numberOfViewsText: "Views",
        noResultsText: "No results found.",
        backToMapButtonText: "Map",
        showMoreResultsGalleryText: "Show more results",
        clearBtnTitle: "Clear",
        addressSearchBtnTitle: "Address Search",
        fullScreenBtnTitle: "Full screen",
        noLegendText: "No Legend",
        sizeUnitKB: "KB",
        sizeUnitMB: "MB",
        itemUnavailableText: "Item unavailable on this device.",
        title: {
            settingsBtnTitle: "Settings",
            itemSearchBtnTitle: "Item Search",
            infoBtnTitle: "Info",
            sortByBtnTitle: "Sort by",
            layoutBtnTitle: "Layout",
            signInBtnTitle: "Sign In",
            signOutBtnTitle: "Sign Out",
            geolocationBtnTitle: "Geolocation",
            ascendingSort: "Ascending",
            descendingSort: "Descending",
            viewBtnTitle: "View",
            backButtonTitle: "Back"
        },
        errorMessages: {
            emptyGroup: "The configured group is not having any data to perform query.",
            invalidSearch: "No results found.",
            invalidBasemapQuery: "Unable to get basemaps group.",
            falseConfigParams: "Required configuration key values are either null or not exactly matching with layer attributes. This message may appear multiple times.",
            invalidLocation: "Current Location not found.",
            invalidProjection: "Unable to project current location on map.",
            widgetNotLoaded: "Failed to load widgets.",
            minfontSizeGreater: "Minimum font size value in configuration settings is greater than maximum value.",
            layerNotFound: "Unable to get data from layers.",
            unableToOpenItem: "Unable to open item.",
            wmsSpatialReferenceError: "Spatial reference of the WMS layer does not match with spatial reference of map.",
            noPublicItems: "There are no public items in the configured group or no items have been shared with this group yet.",
            emptyUsernamePassword: "Please enter Username and Password.",
            noFullScreenSupport: "Current browser does not support full screen mode.",
            notMemberOfOrg: "You are not a member of this organization"
        }
    }),
    "ar": 1,
    "bs": 1,
    "cs": 1,
    "da": 1,
    "de": 1,
    "el": 1,
    "es": 1,
    "et": 1,
    "fi": 1,
    "fr": 1,
    "he": 1,
    "hi": 1,
    "hr": 1,
    "id": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lt": 1,
    "lv": 1,
    "nb": 1,
    "nl": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sr": 1,
    "sv": 1,
    "th": 1,
    "tr": 1,
    "vi": 1,
    "zh-cn": 1,
    "zh-hk": 1,
    "zh-tw": 1
});
